"""Compatibility facade for survey Excel import.

Implementation lives in ``backend.services.survey_import``.
Importing from this module remains supported for routers and tests.
"""

from __future__ import annotations

from backend.services.survey_import import (  # noqa: F401
    ALLOWED_SCHEMAS,
    AUTO_DEFAULT_MARKERS,
    BACKEND_GENERATED_ID_TABLES,
    ColumnMeta,
    DAMAGE_LEVEL_FIELD,
    DAMAGED_PLANT_COUNT_FIELD,
    EMPTY_LOCALITY_LABEL,
    EVENT_TYPE_FIELD,
    EXCEL_DATETIME_EPOCH,
    EXCEL_EPOCH,
    LEDGER_CONFLICT_COLUMNS,
    LEDGER_HISTORY_RULES,
    LOCALITY_FIELD,
    PreparedRow,
    PreparedSheet,
    RECHECK_ABNORMAL_EVENT_TYPE,
    TableMeta,
    UNDAMAGED_LEVELS,
    USE_DEFAULT,
    UseColumnDefault,
    assign_backend_generated_ids,
    build_import_plan,
    build_sheet_stats,
    choose_conflict_columns,
    correct_dispatch_event_types,
    fetch_survey_table_metadata,
    get_header,
    has_errors,
    import_survey_excel,
    insert_row,
    insert_valid_rows,
    is_backend_generated_column,
    is_blank,
    mark_database_duplicates,
    mark_file_duplicates,
    normalize_header_value,
    parse_cell_value,
    parse_excel_date,
    parse_excel_datetime,
    parse_integer,
    parse_rows,
    parse_text,
    resolve_table_conflict_columns,
    row_exists,
    run_survey_excel_import,
    sheet_has_data,
    summarize_import,
    validate_headers,
    validate_required_columns,
)
