-- 新增虫种：杨树食叶害虫
-- 参考其他害虫的数据库设计，字段完全一致
-- 包含：调查表、事件流水表（含事件类型枚举）、台账视图
-- sites.杨树食叶害虫点位基础表 已存在（291 点），复用

BEGIN;

-- ============================================================
-- 1. 事件类型枚举（ledger schema，与其他害虫枚举值一致）
-- ============================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                   WHERE n.nspname = 'ledger' AND t.typname = 'yangshu_shiye_event_type') THEN
        CREATE TYPE ledger.yangshu_shiye_event_type AS ENUM ('调查下派', '防治', '复查异常', '复查合格');
    END IF;
END
$$;

-- ============================================================
-- 2. survey.杨树食叶害虫调查表（字段与其他害虫调查表一致）
-- ============================================================
CREATE TABLE IF NOT EXISTS survey."杨树食叶害虫调查表" (
    "编号" character varying NOT NULL,
    "虫害类型" character varying NOT NULL,
    "调查日期" date NOT NULL,
    "调查结论" character varying NOT NULL,
    "详细描述" text NOT NULL,
    "年份" integer DEFAULT 2026 NOT NULL,
    "点位名称" character varying DEFAULT ''::character varying NOT NULL,
    CONSTRAINT yangshu_shiye_inspection_detail_check CHECK ((btrim("详细描述") <> ''::text)),
    CONSTRAINT yangshu_shiye_inspection_result_check CHECK (((("调查结论")::text = ANY (ARRAY[('发现问题'::character varying)::text, ('未发现问题'::character varying)::text]))))
);

COMMENT ON TABLE survey."杨树食叶害虫调查表" IS '杨树食叶害虫调查表';
COMMENT ON COLUMN survey."杨树食叶害虫调查表"."点位名称" IS '调查记录上的点位名称；工单素材/调查导入优先使用本字段';

ALTER TABLE ONLY survey."杨树食叶害虫调查表"
    ADD CONSTRAINT "杨树食叶害虫调查表_pkey" PRIMARY KEY ("编号", "虫害类型", "调查日期", "年份");

-- ============================================================
-- 3. ledger.杨树食叶害虫问题点位事件流水表（字段与其他害虫流水表一致）
-- ============================================================
CREATE TABLE IF NOT EXISTS ledger."杨树食叶害虫问题点位事件流水表" (
    id integer NOT NULL,
    "事件时间" timestamp without time zone NOT NULL,
    "事件类型" ledger.yangshu_shiye_event_type NOT NULL,
    "虫害类型" character varying NOT NULL,
    "属地" character varying,
    "编号" character varying NOT NULL,
    "点位名称" character varying,
    "寄主树种" character varying,
    "本次调查结论" character varying,
    "本次详细情况" text NOT NULL,
    "备注" text,
    "年份" integer DEFAULT 2026 NOT NULL,
    CONSTRAINT yangshu_shiye_event_detail_check CHECK ((btrim("本次详细情况") <> ''::text)),
    CONSTRAINT yangshu_shiye_event_result_check CHECK (
        "本次调查结论" IS NULL OR "本次调查结论" IN ('发现问题', '未发现问题')
    )
);

ALTER TABLE ONLY ledger."杨树食叶害虫问题点位事件流水表"
    ADD CONSTRAINT "杨树食叶害虫问题点位事件流水表_pkey" PRIMARY KEY (id);

ALTER TABLE ledger."杨树食叶害虫问题点位事件流水表"
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME ledger."杨树食叶害虫问题点位事件流水表_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

CREATE UNIQUE INDEX IF NOT EXISTS yangshu_shiye_event_dedup_idx
    ON ledger."杨树食叶害虫问题点位事件流水表" USING btree ("编号", "虫害类型", "事件类型", "事件时间");

CREATE INDEX IF NOT EXISTS yangshu_shiye_event_lookup_idx
    ON ledger."杨树食叶害虫问题点位事件流水表" USING btree ("编号", "虫害类型", "事件时间" DESC, id DESC);

-- ============================================================
-- 4. ledger.杨树食叶害虫问题点位台账（VIEW，复制其他害虫台账聚合逻辑）
-- ============================================================
DROP VIEW IF EXISTS ledger."杨树食叶害虫问题点位台账";

CREATE VIEW ledger."杨树食叶害虫问题点位台账" AS
WITH base_events AS (
    SELECT e.id,
        e."事件时间",
        e."事件类型",
        e."虫害类型",
        e."属地",
        e."编号",
        e."点位名称",
        e."寄主树种",
        e."本次调查结论",
        e."本次详细情况",
        e."备注",
        e."年份",
        concat(EXTRACT(year FROM e."事件时间")::integer, '/', EXTRACT(month FROM e."事件时间")::integer, '/', EXTRACT(day FROM e."事件时间")::integer) AS event_date_text
    FROM ledger."杨树食叶害虫问题点位事件流水表" e
),
first_info AS (
    SELECT DISTINCT ON (b."编号", b."虫害类型", b."年份") b."编号",
        b."虫害类型",
        b."属地",
        b."点位名称",
        b."寄主树种",
        b."年份"
    FROM base_events b
    ORDER BY b."编号", b."虫害类型", b."年份", b."事件时间", b.id
),
last_event AS (
    SELECT DISTINCT ON (b."编号", b."虫害类型", b."年份") b."编号",
        b."虫害类型",
        b."年份",
        b."事件类型"::text AS last_event_type
    FROM base_events b
    ORDER BY b."编号", b."虫害类型", b."年份", b."事件时间" DESC, b.id DESC
),
dispatch_dates AS (
    SELECT d."编号",
        d."虫害类型",
        d."年份",
        string_agg(d.event_date_text, '、'::text ORDER BY d.event_date) AS "下派日期列表"
    FROM (SELECT DISTINCT b."编号",
            b."虫害类型",
            b."年份",
            b."事件时间"::date AS event_date,
            b.event_date_text
        FROM base_events b
        WHERE b."事件类型"::text = ANY (ARRAY['调查下派'::text, '复查异常'::text])) d
    GROUP BY d."编号", d."虫害类型", d."年份"
),
survey_dates AS (
    SELECT d."编号",
        d."虫害类型",
        d."年份",
        string_agg(d.event_date_text, '、'::text ORDER BY d.event_date) AS "调查日期列表"
    FROM (SELECT DISTINCT b."编号",
            b."虫害类型",
            b."年份",
            b."事件时间"::date AS event_date,
            b.event_date_text
        FROM base_events b
        WHERE b."本次调查结论" IS NOT NULL) d
    GROUP BY d."编号", d."虫害类型", d."年份"
),
treatment_dates AS (
    SELECT d."编号",
        d."虫害类型",
        d."年份",
        string_agg(d.event_date_text, '、'::text ORDER BY d.event_date) AS "防治日期列表"
    FROM (SELECT DISTINCT b."编号",
            b."虫害类型",
            b."年份",
            b."事件时间"::date AS event_date,
            b.event_date_text
        FROM base_events b
        WHERE b."事件类型"::text = '防治'::text) d
    GROUP BY d."编号", d."虫害类型", d."年份"
),
detail_agg AS (
    SELECT b."编号",
        b."虫害类型",
        b."年份",
        string_agg(
            CASE
                WHEN btrim(COALESCE(b."本次详细情况", ''::text)) <> ''::text THEN (((b.event_date_text || ' '::text) || b."事件类型") || '：'::text) || b."本次详细情况"
                ELSE (b.event_date_text || ' '::text) || b."事件类型"
            END, '；'::text ORDER BY b."事件时间", b.id) AS "详细情况"
    FROM base_events b
    GROUP BY b."编号", b."虫害类型", b."年份"
)
SELECT f."编号",
    f."虫害类型",
    f."属地",
    f."点位名称",
    f."寄主树种",
    f."年份",
    COALESCE(dd."下派日期列表", ''::text) AS "下派日期列表",
    COALESCE(sd."调查日期列表", ''::text) AS "调查日期列表",
    COALESCE(td."防治日期列表", ''::text) AS "防治日期列表",
    da."详细情况",
    CASE le.last_event_type
        WHEN '调查下派'::text THEN '待防治'::text
        WHEN '防治'::text THEN '待复查'::text
        WHEN '复查异常'::text THEN '复查异常'::text
        WHEN '复查合格'::text THEN '已闭环'::text
        ELSE NULL::text
    END::character varying AS "当前状态"
FROM first_info f
    JOIN last_event le ON le."编号"::text = f."编号"::text AND le."虫害类型"::text = f."虫害类型"::text AND le."年份" = f."年份"
    LEFT JOIN dispatch_dates dd ON dd."编号"::text = f."编号"::text AND dd."虫害类型"::text = f."虫害类型"::text AND dd."年份" = f."年份"
    LEFT JOIN survey_dates sd ON sd."编号"::text = f."编号"::text AND sd."虫害类型"::text = f."虫害类型"::text AND sd."年份" = f."年份"
    LEFT JOIN treatment_dates td ON td."编号"::text = f."编号"::text AND td."虫害类型"::text = f."虫害类型"::text AND td."年份" = f."年份"
    JOIN detail_agg da ON da."编号"::text = f."编号"::text AND da."虫害类型"::text = f."虫害类型"::text AND da."年份" = f."年份";

COMMIT;
