-- 新增虫种：白蜡蛀干害虫
-- 仅调查表 + 点位基础表，无事件流水 / 台账
-- 点位基础表由 reference.通州白蜡图层 初始化

BEGIN;

-- ============================================================
-- 1. sites.白蜡点位基础表（由通州白蜡图层灌入）
-- ============================================================
CREATE TABLE IF NOT EXISTS sites."白蜡点位基础表" (
    gid integer NOT NULL,
    geom geometry(MultiPolygon, 3857),
    "编号" character varying,
    "属地" character varying,
    "村" character varying,
    "面积" double precision,
    "地块状态" character varying DEFAULT ''::character varying NOT NULL
);

COMMENT ON TABLE sites."白蜡点位基础表" IS '白蜡点位基础表（源自 reference.通州白蜡图层）';
COMMENT ON COLUMN sites."白蜡点位基础表"."村" IS '来源图层字段「村庄」';
COMMENT ON COLUMN sites."白蜡点位基础表"."地块状态" IS '地块状态：空/调查/伐除 等';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = '白蜡点位基础表_pkey'
          AND conrelid = 'sites."白蜡点位基础表"'::regclass
    ) THEN
        ALTER TABLE ONLY sites."白蜡点位基础表"
            ADD CONSTRAINT "白蜡点位基础表_pkey" PRIMARY KEY (gid);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute AS a
        JOIN pg_class AS c ON c.oid = a.attrelid
        JOIN pg_namespace AS n ON n.oid = c.relnamespace
        WHERE n.nspname = 'sites'
          AND c.relname = '白蜡点位基础表'
          AND a.attname = 'gid'
          AND a.attidentity IN ('a', 'd')
    ) THEN
        ALTER TABLE sites."白蜡点位基础表"
            ALTER COLUMN gid ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME sites."白蜡点位基础表_gid_seq"
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1
            );
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS baila_sites_geom_idx
    ON sites."白蜡点位基础表" USING gist (geom);

CREATE INDEX IF NOT EXISTS baila_sites_code_idx
    ON sites."白蜡点位基础表" USING btree ("编号");

-- 幂等灌入：表为空时从通州白蜡图层复制
INSERT INTO sites."白蜡点位基础表" (gid, geom, "编号", "属地", "村", "面积", "地块状态")
SELECT
    r.id,
    r.geom,
    r."编号",
    r."属地",
    r."村庄",
    r."面积",
    COALESCE(BTRIM(r."地块状态"), '')
FROM reference."通州白蜡图层" AS r
WHERE NOT EXISTS (SELECT 1 FROM sites."白蜡点位基础表" LIMIT 1);

-- 同步 identity 序列，避免后续新增编号冲突
SELECT setval(
    pg_get_serial_sequence('sites."白蜡点位基础表"', 'gid'),
    GREATEST(COALESCE((SELECT MAX(gid) FROM sites."白蜡点位基础表"), 1), 1),
    true
);

-- ============================================================
-- 2. survey.白蜡蛀干害虫调查表
-- ============================================================
CREATE TABLE IF NOT EXISTS survey."白蜡蛀干害虫调查表" (
    "编号" character varying NOT NULL,
    "属地" character varying NOT NULL,
    "调查日期" date NOT NULL,
    "目测死亡（株）" integer DEFAULT 0 NOT NULL,
    "伐除（株）" integer DEFAULT 0 NOT NULL,
    "换植（株）" integer DEFAULT 0 NOT NULL,
    "窄吉丁危害（株）" integer DEFAULT 0 NOT NULL,
    "窄吉丁孔数（个）" integer DEFAULT 0 NOT NULL,
    "木蠹蛾危害（株）" integer DEFAULT 0 NOT NULL,
    "备注" text DEFAULT ''::text NOT NULL,
    "年份" integer DEFAULT 2026 NOT NULL
);

COMMENT ON TABLE survey."白蜡蛀干害虫调查表" IS '白蜡蛀干害虫调查表';
COMMENT ON COLUMN survey."白蜡蛀干害虫调查表"."年份" IS '业务年份；导出筛选与数据管理用，默认可由导入模板填写';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = '白蜡蛀干害虫调查表_pkey'
          AND conrelid = 'survey."白蜡蛀干害虫调查表"'::regclass
    ) THEN
        ALTER TABLE ONLY survey."白蜡蛀干害虫调查表"
            ADD CONSTRAINT "白蜡蛀干害虫调查表_pkey" PRIMARY KEY ("编号", "调查日期", "年份");
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS baila_zhugan_survey_date_idx
    ON survey."白蜡蛀干害虫调查表" USING btree ("调查日期");

CREATE INDEX IF NOT EXISTS baila_zhugan_survey_locality_idx
    ON survey."白蜡蛀干害虫调查表" USING btree ("属地");

COMMIT;
